template_screen_size(1600, 900)
set_skip_img('get_item.png', 'get_item.png')
click('load.png')
click('close_info_panel.png')
click('close_info_panel.png')
click('shop.png')
click('credit_shop.png | credit_shop1.png')
click('get_credit.png')
click_if_exist('75off.png | buy.png')
